# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

name: fetch_run_jar_file

on:
  workflow_dispatch:
    inputs:
      env: 
        description: 'Environment Name'
        default: 'dev'
        required: true
      suite_name:
        description: 'Suite Name'
        default: 'smoke'
        required: true
      server:
        description: 'Server Name'
        default: 'azure'
        required: true
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download a single artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build_jar_file.yml
        run_id: 3502980828
        repo: ${{ github.repository }}
        name: Test-Jar
        path: TestProject/actions/runs/3502980828
        
     
