# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      env: 
        description: 'Environment Name'
        default: 'dev'
        required: true
      suite_name:
        description: 'Suite Name'
        default: 'smoke'
        required: true
      server:
        description: 'Server Name'
        default: 'azure'
        required: true
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test -Denv=${{github.event.inputs.env}},${{github.event.inputs.suite_name}},${{github.event.inputs.server}},${{secrets.USERNAME}} -file PracticeProject/pom.xml
    - name: Deploy automation report
      uses: actions/upload-artifact@v3
      with:
        name: TestExecutionReport.html
        path: PracticeProject/reports/TestExecutionReport.html
        retention-days: 2
